-- ============================================
-- Resume Analyzer - Database Schema
-- ============================================
-- This file serves as a reference for the database structure.
-- Tables are auto-created on server startup via config/db.js.
-- ============================================

-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS resume_analyzer
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE resume_analyzer;

-- ============================================
-- Users Table
-- Stores user info synced from Firebase Auth.
-- The 'role' column supports admin panel features.
-- ============================================
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firebase_uid VARCHAR(128) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  role ENUM('user', 'admin') DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_firebase_uid (firebase_uid),
  INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Resumes Table
-- Stores uploaded resume files, extracted text,
-- ATS scores, and full analysis results (JSON).
-- ============================================
CREATE TABLE IF NOT EXISTS resumes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  resume_text LONGTEXT,
  file_size INT DEFAULT 0,
  ats_score INT DEFAULT NULL,
  analysis_data JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Suggestions Table
-- Stores individual improvement suggestions
-- generated by AI for each resume analysis.
-- ============================================
CREATE TABLE IF NOT EXISTS suggestions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  resume_id INT NOT NULL,
  suggestion TEXT NOT NULL,
  FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
  INDEX idx_resume_id (resume_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Missing Skills Table
-- Stores skills the AI identified as missing
-- from the resume during analysis.
-- ============================================
CREATE TABLE IF NOT EXISTS missing_skills (
  id INT AUTO_INCREMENT PRIMARY KEY,
  resume_id INT NOT NULL,
  skill VARCHAR(100) NOT NULL,
  FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
  INDEX idx_resume_id (resume_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Job Matches Table
-- Stores results of resume-to-job-description
-- matching, including match % and improvements.
-- ============================================
CREATE TABLE IF NOT EXISTS job_matches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  resume_id INT NOT NULL,
  job_description TEXT,
  match_percentage INT DEFAULT NULL,
  missing_keywords TEXT,
  improvements TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (resume_id) REFERENCES resumes(id) ON DELETE CASCADE,
  INDEX idx_resume_id (resume_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
