/**
 * ============================================
 * Resume Model
 * ============================================
 * Handles all database operations for resumes,
 * including related suggestions, missing skills,
 * and job matches. Uses JOINs for rich queries.
 * ============================================
 */

const ResumeModel = {
  /**
   * Create a new resume record after file upload.
   * @param {object} pool - MySQL connection pool
   * @param {object} data - { user_id, file_name, resume_text, file_size }
   * @returns {number} The new resume's ID
   */
  create: async (pool, data) => {
    const { user_id, file_name, resume_text, file_size } = data;
    const [result] = await pool.query(
      'INSERT INTO resumes (user_id, file_name, resume_text, file_size) VALUES (?, ?, ?, ?)',
      [user_id, file_name, resume_text, file_size || 0]
    );
    return result.insertId;
  },

  /**
   * Update a resume with analysis results (ATS score + full analysis JSON).
   * @param {object} pool - MySQL connection pool
   * @param {number} resumeId - Resume ID
   * @param {object} data - { ats_score, analysis_data }
   * @returns {boolean} True if the update succeeded
   */
  updateAnalysis: async (pool, resumeId, data) => {
    const { ats_score, analysis_data } = data;
    const [result] = await pool.query(
      'UPDATE resumes SET ats_score = ?, analysis_data = ? WHERE id = ?',
      [ats_score, JSON.stringify(analysis_data), resumeId]
    );
    return result.affectedRows > 0;
  },

  /**
   * Save suggestions generated by AI for a resume.
   * Uses a batch insert for efficiency.
   * @param {object} pool - MySQL connection pool
   * @param {number} resumeId - Resume ID
   * @param {string[]} suggestions - Array of suggestion strings
   */
  saveSuggestions: async (pool, resumeId, suggestions) => {
    if (!suggestions || suggestions.length === 0) return;

    const values = suggestions.map(s => [resumeId, s]);
    await pool.query(
      'INSERT INTO suggestions (resume_id, suggestion) VALUES ?',
      [values]
    );
  },

  /**
   * Save missing skills identified by AI for a resume.
   * Uses a batch insert for efficiency.
   * @param {object} pool - MySQL connection pool
   * @param {number} resumeId - Resume ID
   * @param {string[]} skills - Array of skill strings
   */
  saveMissingSkills: async (pool, resumeId, skills) => {
    if (!skills || skills.length === 0) return;

    const values = skills.map(s => [resumeId, s]);
    await pool.query(
      'INSERT INTO missing_skills (resume_id, skill) VALUES ?',
      [values]
    );
  },

  /**
   * Save a job match result.
   * @param {object} pool - MySQL connection pool
   * @param {object} data - { resume_id, job_description, match_percentage, missing_keywords, improvements }
   * @returns {number} The new job match's ID
   */
  saveJobMatch: async (pool, data) => {
    const { resume_id, job_description, match_percentage, missing_keywords, improvements } = data;
    const [result] = await pool.query(
      `INSERT INTO job_matches (resume_id, job_description, match_percentage, missing_keywords, improvements)
       VALUES (?, ?, ?, ?, ?)`,
      [
        resume_id,
        job_description,
        match_percentage,
        JSON.stringify(missing_keywords),
        JSON.stringify(improvements),
      ]
    );
    return result.insertId;
  },

  /**
   * Find a resume by ID with all related data (suggestions, missing skills, job matches).
   * Also includes the owner's name and email.
   * @param {object} pool - MySQL connection pool
   * @param {number} resumeId - Resume ID
   * @returns {object|null} Full resume object with nested arrays, or null
   */
  findById: async (pool, resumeId) => {
    // Get the resume with user info
    const [resumes] = await pool.query(
      `SELECT r.*, u.name AS user_name, u.email AS user_email
       FROM resumes r
       JOIN users u ON r.user_id = u.id
       WHERE r.id = ?`,
      [resumeId]
    );

    if (resumes.length === 0) return null;

    const resume = resumes[0];

    // Parse analysis_data if it's a string
    if (resume.analysis_data && typeof resume.analysis_data === 'string') {
      try {
        resume.analysis_data = JSON.parse(resume.analysis_data);
      } catch (_) { /* leave as-is if parsing fails */ }
    }

    // Get associated suggestions
    const [suggestions] = await pool.query(
      'SELECT id, suggestion FROM suggestions WHERE resume_id = ?',
      [resumeId]
    );
    resume.suggestions = suggestions;

    // Get associated missing skills
    const [missingSkills] = await pool.query(
      'SELECT id, skill FROM missing_skills WHERE resume_id = ?',
      [resumeId]
    );
    resume.missing_skills = missingSkills;

    // Get associated job matches
    const [jobMatches] = await pool.query(
      'SELECT * FROM job_matches WHERE resume_id = ? ORDER BY created_at DESC',
      [resumeId]
    );

    // Parse JSON fields in job matches
    resume.job_matches = jobMatches.map(jm => ({
      ...jm,
      missing_keywords: jm.missing_keywords ? JSON.parse(jm.missing_keywords) : [],
      improvements: jm.improvements ? JSON.parse(jm.improvements) : [],
    }));

    return resume;
  },

  /**
   * Get all resumes for a specific user (history).
   * Returns a summary without full text for performance.
   * @param {object} pool - MySQL connection pool
   * @param {number} userId - User ID
   * @returns {Array} Array of resume summaries
   */
  findByUserId: async (pool, userId) => {
    const [rows] = await pool.query(
      `SELECT r.id, r.file_name, r.file_size, r.ats_score, r.created_at,
              (SELECT COUNT(*) FROM suggestions s WHERE s.resume_id = r.id) AS suggestion_count,
              (SELECT COUNT(*) FROM missing_skills ms WHERE ms.resume_id = r.id) AS missing_skill_count,
              (SELECT COUNT(*) FROM job_matches jm WHERE jm.resume_id = r.id) AS job_match_count
       FROM resumes r
       WHERE r.user_id = ?
       ORDER BY r.created_at DESC`,
      [userId]
    );
    return rows;
  },

  /**
   * Get all resumes across all users (admin feature).
   * Includes user info for each resume.
   * @param {object} pool - MySQL connection pool
   * @returns {Array} Array of resume records with user info
   */
  findAll: async (pool) => {
    const [rows] = await pool.query(
      `SELECT r.id, r.file_name, r.file_size, r.ats_score, r.created_at,
              u.id AS user_id, u.name AS user_name, u.email AS user_email
       FROM resumes r
       JOIN users u ON r.user_id = u.id
       ORDER BY r.created_at DESC`
    );
    return rows;
  },

  /**
   * Delete a resume by ID.
   * Cascading deletes handle suggestions, missing_skills, and job_matches.
   * @param {object} pool - MySQL connection pool
   * @param {number} resumeId - Resume ID
   * @returns {boolean} True if deletion succeeded
   */
  deleteById: async (pool, resumeId) => {
    const [result] = await pool.query(
      'DELETE FROM resumes WHERE id = ?',
      [resumeId]
    );
    return result.affectedRows > 0;
  },

  /**
   * Get aggregate stats about resumes (admin dashboard).
   * @param {object} pool - MySQL connection pool
   * @returns {object} { totalResumes, averageAtsScore, recentResumes, scoreDistribution }
   */
  getStats: async (pool) => {
    // Total resume count
    const [[{ totalResumes }]] = await pool.query(
      'SELECT COUNT(*) AS totalResumes FROM resumes'
    );

    // Average ATS score (only for analyzed resumes)
    const [[{ averageAtsScore }]] = await pool.query(
      'SELECT ROUND(AVG(ats_score)) AS averageAtsScore FROM resumes WHERE ats_score IS NOT NULL'
    );

    // Resumes uploaded in the last 7 days
    const [[{ recentResumes }]] = await pool.query(
      'SELECT COUNT(*) AS recentResumes FROM resumes WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)'
    );

    // Total job matches performed
    const [[{ totalJobMatches }]] = await pool.query(
      'SELECT COUNT(*) AS totalJobMatches FROM job_matches'
    );

    // ATS score distribution (for a chart)
    const [scoreDistribution] = await pool.query(
      `SELECT
        CASE
          WHEN ats_score BETWEEN 0 AND 20 THEN '0-20'
          WHEN ats_score BETWEEN 21 AND 40 THEN '21-40'
          WHEN ats_score BETWEEN 41 AND 60 THEN '41-60'
          WHEN ats_score BETWEEN 61 AND 80 THEN '61-80'
          WHEN ats_score BETWEEN 81 AND 100 THEN '81-100'
        END AS score_range,
        COUNT(*) AS count
       FROM resumes
       WHERE ats_score IS NOT NULL
       GROUP BY score_range
       ORDER BY score_range`
    );

    return {
      totalResumes,
      averageAtsScore: averageAtsScore || 0,
      recentResumes,
      totalJobMatches,
      scoreDistribution,
    };
  },
};

module.exports = ResumeModel;
